"use client";
import { useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

export default function VerifyCertificatePage(){
 const [token,setToken]=useState(""); const [loading,setLoading]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState("");
 const verify=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError("");setResult(null);try{const res=await fetch(`${API_URL}/api/v1/academic-operations/certificates/verify/${encodeURIComponent(token.trim())}`);if(!res.ok)throw new Error("Certificate not found");const data=await res.json();if(!data?.length)throw new Error("Certificate not found");setResult(data[0]);}catch(err){setError((err as Error).message)}finally{setLoading(false)}};
 return <main className="min-h-screen bg-slate-50 px-5 py-16"><div className="mx-auto max-w-2xl"><div className="text-center"><div className="text-3xl font-black tracking-[-.06em] text-brand">bxbii<span className="text-accent">.</span></div><p className="mt-3 text-xs font-bold uppercase tracking-[.2em] text-slate-400">Certificate Verification</p><h1 className="mt-4 text-4xl font-black tracking-tight text-slate-950">Verify a certificate</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">Enter the verification code printed on the certificate to confirm its authenticity.</p></div><form onSubmit={verify} className="mt-10 rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-8"><label className="text-xs font-bold text-slate-600">Verification code</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input required value={token} onChange={e=>setToken(e.target.value)} placeholder="Enter verification token" className="h-12 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-brand/40 focus:bg-white"/><button disabled={loading} className="h-12 rounded-xl bg-brand px-6 text-sm font-black text-white disabled:opacity-50">{loading?"Checking…":"Verify"}</button></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}. Please check the code and try again.</div>}</form>{result&&<div className="mt-5 rounded-3xl border border-emerald-200 bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-50 text-xl text-emerald-600">✓</div><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Verified</p><h2 className="text-xl font-black text-slate-950">Certificate is valid</h2></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Info label="Certificate number" value={result.certificate_no}/><Info label="English title" value={result.title_en}/><Info label="العنوان" value={result.title_ar}/><Info label="Issue date" value={String(result.issue_date).slice(0,10)}/><Info label="Status" value={result.status}/></div></div>}<div className="mt-8 text-center text-xs text-slate-400">© {new Date().getFullYear()} bxbii Cloud · Secure certificate verification</div></div></main>
}
function Info({label,value}:{label:string;value:any}){return <div><div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 font-semibold text-slate-800">{value||"—"}</div></div>}
