"use client";
import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { operationsApi, OperationsData } from "@/lib/operations-api";

const MODULES = [
 {slug:"admissions",title:"Admissions & CRM",ar:"القبول وCRM",desc:"Leads, applications and follow-up pipeline.",icon:"◎",key:"crm"},
 {slug:"timetable",title:"Timetable",ar:"الجدول الدراسي",desc:"Sessions, rooms, trainers and weekly delivery.",icon:"▦",key:"sessions"},
 {slug:"attendance",title:"Attendance",ar:"الحضور والانصراف",desc:"Attendance, absences and excuse workflow.",icon:"✓",key:"attendance"},
 {slug:"exams",title:"Exams & Assessments",ar:"الاختبارات والتقييم",desc:"Assessments, scores, grades and progression.",icon:"▤",key:"assessments"},
 {slug:"certificates",title:"Certificates",ar:"الشهادات",desc:"Issuance, verification and certificate archive.",icon:"◇",key:"certificates"},
 {slug:"reports",title:"Reports & Analytics",ar:"التقارير والتحليلات",desc:"Executive KPIs across academic operations.",icon:"◫",key:"overview"},
 {slug:"settings",title:"System Settings",ar:"إعدادات النظام",desc:"Configuration, roles, numbering and integrations.",icon:"⚙",key:"overview"},
] as const;

type Module = typeof MODULES[number];

export function OperationsCenter({active}:{active?:string}){
 const [data,setData]=useState<OperationsData>({rooms:[],sessions:[],attendance:[],assessments:[],certificates:[],crm:[]});
 const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const reload=()=>{setLoading(true);operationsApi.overview().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(reload,[]);
 const current=MODULES.find(x=>x.slug===active);
 if(current) return <ModuleView module={current} data={data} loading={loading} error={error} reload={reload}/>;
 return <Home data={data} loading={loading} error={error}/>;
}

function Home({data,loading,error}:{data:OperationsData;loading:boolean;error:string}){
 const cards=[["Learners","Students module","/students"],["Admissions & CRM",`${data.crm.length} activities`,"/operations/admissions"],["Timetable",`${data.sessions.length} sessions`,"/operations/timetable"],["Attendance",`${data.attendance.length} records`,"/operations/attendance"],["Assessments",`${data.assessments.length} records`,"/operations/exams"],["Certificates",`${data.certificates.length} issued`,"/operations/certificates"]];
 return <div className="space-y-7" dir="ltr"><Header title="Institute Operations" sub="One workspace for admissions, academic delivery, attendance, assessment and certification."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(([title,meta,href])=><Link key={href} href={href} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-brand/30 hover:shadow-lg"><div className="text-lg font-black text-slate-950">{title}</div><div className="mt-2 text-sm text-slate-500">{meta}</div><div className="mt-5 text-xs font-bold text-brand">Open workspace →</div></Link>)}</div>{loading&&<Notice>Loading live operational data…</Notice>}{error&&<Notice>{error}</Notice>}<div className="grid gap-4 sm:grid-cols-3"><Kpi label="Rooms" value={data.rooms.length}/><Kpi label="Sessions" value={data.sessions.length}/><Kpi label="Certificates" value={data.certificates.length}/></div></div>
}

function ModuleView({module,data,loading,error,reload}:{module:Module;data:OperationsData;loading:boolean;error:string;reload:()=>void}){
 const [open,setOpen]=useState(false);
 const rows=(data[module.key as keyof OperationsData]||[]) as any[];
 const columns=module.slug==="timetable"?["Date","Time","Topic","Status"]:module.slug==="attendance"?["Student","Session","Status","Excuse"]:module.slug==="exams"?["Assessment","Type","Score","Grade"]:module.slug==="certificates"?["Certificate","Title","Issue date","Status"]:["Reference","Type","Details","Status"];
 return <div className="space-y-6" dir="ltr"><Header title={module.title} sub={module.desc} ar={module.ar}/><div className="flex flex-wrap gap-2"><Link href="/operations" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold text-slate-700">← All modules</Link>{module.slug!=="reports"&&module.slug!=="settings"&&<button onClick={()=>setOpen(true)} className="rounded-xl bg-brand px-4 py-2 text-sm font-bold text-white shadow-lg shadow-brand/15">+ New record</button>}<button onClick={reload} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold text-slate-600">↻ Refresh</button></div><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Records" value={rows.length}/><Kpi label="Rooms" value={data.rooms.length}/><Kpi label="Today" value={rows.filter(x=>String(x.session_date||"").slice(0,10)===new Date().toISOString().slice(0,10)).length}/></div>{loading?<Notice>Loading live records…</Notice>:error?<Notice>{error}</Notice>:<div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Operational queue</h2><p className="mt-1 text-xs text-slate-400">Connected to the bxbii Cloud academic operations API.</p></div>{rows.length?<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr>{columns.map(c=><th key={c} className="px-5 py-3">{c}</th>)}</tr></thead><tbody className="divide-y">{rows.slice(0,100).map((x,i)=><tr key={x.id||i} className="hover:bg-slate-50">{columns.map((_,j)=><td key={j} className={`px-5 py-4 ${j===0?"font-semibold text-slate-800":"text-slate-500"}`}>{cell(module.slug,x,j)}</td>)}</tr>)}</tbody></table></div>:<div className="p-12 text-center text-sm text-slate-400">No records yet. Create the first record from this workspace.</div>}</div>}{open&&<RecordModal module={module} data={data} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);reload()}}/>}</div>
}

function RecordModal({module,data,onClose,onSaved}:{module:Module;data:OperationsData;onClose:()=>void;onSaved:()=>void}){
 const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [form,setForm]=useState<Record<string,string>>({});
 const set=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{
   if(module.slug==="admissions") await operationsApi.createCrm({studentId:form.studentId||undefined,activityType:form.activityType||"LEAD",subject:form.subject,details:form.details,nextActionAt:form.nextActionAt||undefined,status:form.status||"OPEN"});
   else if(module.slug==="timetable") await operationsApi.createSession({batchId:form.batchId,trainerId:form.trainerId||undefined,roomId:form.roomId||undefined,sessionDate:form.sessionDate,startTime:form.startTime,endTime:form.endTime,topic:form.topic,status:form.status||"SCHEDULED",notes:form.notes});
   else if(module.slug==="attendance") await operationsApi.markAttendance({sessionId:form.sessionId,studentId:form.studentId,status:form.status||"PRESENT",checkInAt:form.checkInAt||undefined,excuseStatus:form.excuseStatus||"NONE",excuseNote:form.excuseNote});
   else if(module.slug==="exams") await operationsApi.createAssessment({batchId:form.batchId,studentId:form.studentId,title:form.title,assessmentType:form.assessmentType||"EXAM",maxScore:Number(form.maxScore||100),score:form.score===""?undefined:Number(form.score),grade:form.grade||undefined,status:form.status||"PENDING",assessedAt:form.assessedAt||undefined,notes:form.notes});
   else if(module.slug==="certificates") await operationsApi.issueCertificate({studentId:form.studentId,batchId:form.batchId||undefined,certificateNo:form.certificateNo||undefined,certificateType:form.certificateType||"COMPLETION",titleAr:form.titleAr||"شهادة إتمام",titleEn:form.titleEn||"Certificate of Completion",issueDate:form.issueDate||undefined});
   onSaved();
 }catch(err){setError((err as Error).message)}finally{setBusy(false)}};
 const fields=module.slug==="admissions"?[['studentId','Student ID'],['activityType','Activity type'],['subject','Subject'],['details','Details'],['nextActionAt','Next action (date/time)'],['status','Status']]:module.slug==="timetable"?[['batchId','Batch ID'],['trainerId','Trainer ID'],['roomId','Room ID'],['sessionDate','Session date'],['startTime','Start time'],['endTime','End time'],['topic','Topic'],['status','Status'],['notes','Notes']]:module.slug==="attendance"?[['sessionId','Session ID'],['studentId','Student ID'],['status','Attendance status'],['checkInAt','Check-in time'],['excuseStatus','Excuse status'],['excuseNote','Excuse note']]:module.slug==="exams"?[['batchId','Batch ID'],['studentId','Student ID'],['title','Assessment title'],['assessmentType','Assessment type'],['maxScore','Maximum score'],['score','Score'],['grade','Grade'],['status','Status'],['assessedAt','Assessed at'],['notes','Notes']]:[['studentId','Student ID'],['batchId','Batch ID'],['certificateNo','Certificate number (optional)'],['certificateType','Certificate type'],['titleAr','Arabic title'],['titleEn','English title'],['issueDate','Issue date']];
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-brand">bxbii Cloud</p><h2 className="mt-2 text-2xl font-black text-slate-950">New {module.title} record</h2><p className="mt-1 text-sm text-slate-500">Save directly to the academic operations database.</p></div><button type="button" onClick={onClose} className="rounded-xl border px-3 py-2 text-slate-500">✕</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className={key==="details"||key==="notes"||key==="excuseNote"?"sm:col-span-2":""}><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span>{["details","notes","excuseNote"].includes(key)?<textarea value={form[key]||""} onChange={e=>set(key,e.target.value)} className="min-h-24 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-brand/40 focus:bg-white"/>:<input required={!['trainerId','roomId','certificateNo','batchId','details','notes','checkInAt','nextActionAt','issueDate','score','grade','excuseNote'].includes(key)} type={key.toLowerCase().includes('date')||key.toLowerCase().includes('at')?'datetime-local':'text'} value={form[key]||""} onChange={e=>set(key,e.target.value)} placeholder={label} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-brand/40 focus:bg-white"/>}</label>)}</div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="mt-7 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-5 py-2.5 text-sm font-bold text-slate-600">Cancel</button><button disabled={busy} className="rounded-xl bg-brand px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?"Saving…":"Save record"}</button></div></form></div>
}

function cell(slug:string,x:any,j:number){if(slug==="timetable")return [x.session_date,`${x.start_time||""} – ${x.end_time||""}`,x.topic||"General session",x.status][j];if(slug==="attendance")return [x.student_id,x.session_id,x.status,x.excuse_status][j];if(slug==="exams")return [x.title,x.assessment_type,x.score==null?"Pending":`${x.score}/${x.max_score}`,x.grade||"—"][j];if(slug==="certificates")return [x.certificate_no,x.title_en,x.issue_date,x.status][j];return [x.id,x.activity_type||"—",x.subject||x.details||"—",x.status||"—"][j]}
function Header({title,sub,ar}:{title:string;sub:string;ar?:string}){return <div><div className="text-xs font-bold uppercase tracking-[.18em] text-brand">bxbii Cloud</div><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{sub}</p>{ar&&<p className="mt-1 text-sm font-semibold text-slate-700" dir="rtl">{ar}</p>}</div>}
function Kpi({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</div><div className="mt-2 text-3xl font-black text-slate-950">{value}</div></div>}
function Notice({children}:{children:ReactNode}){return <div className="rounded-2xl border bg-white p-5 text-sm text-slate-500">{children}</div>}
