import { notFound } from "next/navigation";
import Link from "next/link";
import { catalogPrograms } from "@/lib/site-catalog";

export async function generateStaticParams() { return catalogPrograms.map((p) => ({ slug: p.slug })); }
export const dynamicParams = false;

export default function Page({ params }: { params: { slug: string } }) {
  const p = catalogPrograms.find((x) => x.slug === params.slug);
  if (!p) notFound();
  return <main className="bg-white"><section className="bg-[#08172e] py-24 text-white"><div className="mx-auto max-w-5xl px-5 sm:px-8"><Link href="/programs" className="text-sm font-bold text-blue-300">← Programs / البرامج</Link><span className="mt-10 block text-xs font-black uppercase tracking-[.18em] text-blue-300">{p.domain.en} / {p.domain.ar}</span><h1 className="mt-4 text-5xl font-black tracking-tight">{p.name.en}</h1><h2 className="mt-3 text-2xl font-bold text-white/80" dir="rtl">{p.name.ar}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-white/65">{p.description.en}</p><p className="mt-2 max-w-3xl text-lg leading-8 text-white/65" dir="rtl">{p.description.ar}</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full bg-white/10 px-4 py-2 text-sm">{p.duration.en}</span><span className="rounded-full bg-white/10 px-4 py-2 text-sm">{p.level.en}</span><span className="rounded-full bg-white/10 px-4 py-2 text-sm">{p.type.en}</span></div></div></section><section className="py-20"><div className="mx-auto max-w-5xl px-5 sm:px-8"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl border border-slate-200 p-7"><b>01 · Practical</b><p className="mt-3 text-sm leading-6 text-slate-500">Projects, exercises and applied assessment.</p></div><div className="rounded-3xl border border-slate-200 p-7"><b>02 · Bilingual</b><p className="mt-3 text-sm leading-6 text-slate-500">Learning information in Arabic and English.</p></div><div className="rounded-3xl border border-slate-200 p-7"><b>03 · Industry</b><p className="mt-3 text-sm leading-6 text-slate-500">Designed around real workplace capability.</p></div></div><div className="mt-12 rounded-3xl bg-slate-50 p-8 text-center"><h2 className="text-3xl font-black">{p.name.en}</h2><p className="mt-3 text-slate-500">{p.name.ar} · {p.duration.en}</p><Link href="/contact-us" className="mt-6 inline-flex rounded-full bg-accent px-7 py-3 font-black text-white">Register interest / سجّل اهتمامك</Link></div></div></section></main>;
}
