"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useLanguage } from "./language-provider";
import { publicApi, type PublicCourse } from "@/lib/public-api";

export function CoursesPage(){
 const {lang}=useLanguage(); const ar=lang==="ar"; const [courses,setCourses]=useState<PublicCourse[]>([]); const t=(e:string,a:string)=>ar?a:e;
 useEffect(()=>{publicApi.getCourses().then(r=>setCourses(r??[])).catch(()=>setCourses([]))},[]);
 return <main className="bg-white"><section className="bg-[#08172e] py-24 text-white"><div className={`mx-auto max-w-7xl px-5 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><span className="text-xs font-black uppercase tracking-[.18em] text-blue-300">{t("COURSES","الدورات")}</span><h1 className="mt-4 max-w-4xl text-5xl font-black tracking-tight sm:text-6xl">{t("Training content published on BXBII.","المحتوى التدريبي المنشور في BXBII.")}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/65">{t("Browse the courses currently available in the platform database.","استعرض الدورات المتوفرة حاليًا في قاعدة بيانات المنصة.")}</p></div></section><section className="py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">{courses.length===0?<div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-400">{t("No courses are currently published.","لا توجد دورات منشورة حاليًا.")}</div>:<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{courses.map(c=><Link href={c.hrefOverride||`/courses/${c.slug}`} key={c.id} className="group rounded-[1.5rem] border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-accent hover:shadow-xl"><span className="text-xs font-black text-accent">{c.status==="OPEN"?t("Open","مفتوح"):t("Coming soon","قريبًا")}</span><h2 className={`mt-3 text-2xl font-black text-slate-950 group-hover:text-brand ${ar?"text-right":""}`}>{ar?c.arTitle:c.enTitle}</h2><p className={`mt-3 leading-7 text-slate-500 ${ar?"text-right":""}`}>{ar?c.arDescription:c.enDescription}</p><div className={`mt-6 border-t border-slate-100 pt-4 text-xs font-bold text-slate-400 ${ar?"text-right":""}`}>{ar?c.arDuration:c.enDuration} · {ar?c.arFormat:c.enFormat}</div></Link>)}</div>}</div></section></main>;
}
