"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { publicApi } from "@/lib/public-api";
import { useLanguage } from "./language-provider";

type PageKey="technology"|"solutions"|"industries"|"rd"|"about"|"contact"|"impact";
const pages:Record<PageKey,{e:string;a:string;t:string;ta:string;i:string;ia:string;c:Array<[string,string,string,string]>}>={
technology:{e:"TECHNOLOGY STACK",a:"منظومة التقنية",t:"Engineering the intelligence layer of the physical world",ta:"نهندس طبقة الذكاء للعالم المادي",i:"bxbii brings together semiconductor design, embedded systems, sensing, connected devices, robotics and physical AI into an integrated technology stack.",ia:"تجمع bxbii بين تصميم أشباه الموصلات والأنظمة المدمجة والاستشعار والأجهزة المتصلة والروبوتات والذكاء الاصطناعي الفيزيائي ضمن منظومة متكاملة.",c:[["01","Semiconductor Design","تصميم أشباه الموصلات","Chip, electronics architecture and hardware-oriented product development."],["02","Embedded Systems","الأنظمة المدمجة","Reliable hardware/software foundations for connected and critical devices."],["03","Sensors & IoT","الحساسات وإنترنت الأشياء","Connected sensing, telemetry and digital-twin foundations for industry."],["04","Robotics & Physical AI","الروبوتات والذكاء الفيزيائي","Perception, computer vision and robotic systems connecting intelligence with action."]]},
solutions:{e:"SOLUTIONS",a:"الحلول",t:"From industrial challenge to deployable technology",ta:"من التحدي الصناعي إلى تقنية قابلة للتطبيق",i:"We engineer technology around measurable operational problems — inspection, monitoring, safety, asset visibility and automation.",ia:"نطوّر التقنية حول تحديات تشغيلية قابلة للقياس — التفتيش والمراقبة والسلامة ورؤية الأصول والأتمتة.",c:[["01","Industrial Inspection","التفتيش الصناعي","Computer vision, sensors and robotic systems for inspection workflows."],["02","Safety & Monitoring","السلامة والمراقبة","Continuous sensing and intelligent alerts for demanding environments."],["03","Predictive Maintenance","الصيانة التنبؤية","Connected equipment data and analytics for maintenance visibility."],["04","Smart Infrastructure","البنية الأساسية الذكية","Integrated sensing, edge intelligence and connected systems for critical assets."]]},
industries:{e:"INDUSTRIES",a:"القطاعات",t:"Technology for environments where reliability matters",ta:"تقنية للبيئات التي تتطلب الاعتمادية",i:"bxbii focuses on industrial and infrastructure contexts where early detection, safety, uptime and operational intelligence create tangible value.",ia:"تركز bxbii على البيئات الصناعية والبنية الأساسية حيث يصنع الكشف المبكر والسلامة واستمرارية التشغيل والذكاء التشغيلي قيمة ملموسة.",c:[["01","Oil & Gas","النفط والغاز","Inspection, monitoring, safety and operational intelligence."],["02","Mining & Manufacturing","التعدين والتصنيع","Equipment visibility, defect detection and industrial automation."],["03","Energy & Utilities","الطاقة والمرافق","Connected assets, monitoring and predictive operations."],["04","Ports, Airports & Infrastructure","الموانئ والمطارات والبنية الأساسية","Technology for critical assets and field operations."]]},
rd:{e:"R&D",a:"البحث والتطوير",t:"Build, test, learn — then move technology into the field",ta:"نبني ونختبر ونتعلم — ثم ننقل التقنية إلى الميدان",i:"Our R&D connects technical exploration with real-world use cases, partnerships and product pathways.",ia:"يربط البحث والتطوير لدينا الاستكشاف التقني بحالات استخدام واقعية وشراكات ومسارات للمنتجات.",c:[["01","Applied AI","الذكاء الاصطناعي التطبيقي","Models and computer vision for industrial perception and decision support."],["02","Edge & Embedded","الحوسبة الطرفية والأنظمة المدمجة","Efficient intelligence close to sensors, devices and machines."],["03","Robotics","الروبوتات","Robotic platforms for inspection, monitoring and controlled field tasks."],["04","Prototyping","النمذجة التقنية","Rapid validation of hardware, software and integrated systems."]]},
about:{e:"ABOUT BXBII",a:"عن bxbii",t:"An Omani deep-tech company building for the real world",ta:"شركة عُمانية للتكنولوجيا العميقة تبني حلولًا للعالم الحقيقي",i:"bxbii creates and integrates hardware, intelligent systems and connected technologies from Oman for regional and international opportunities.",ia:"تطوّر bxbii وتدمج الأجهزة والأنظمة الذكية والتقنيات المتصلة من عُمان للفرص الإقليمية والدولية.",c:[["01","Core Business","النشاط الأساسي","Semiconductors, robotics, IoT, embedded systems and industrial AI."],["02","Engineering Mindset","عقلية هندسية","Technology developed around use cases, constraints and deployment realities."],["03","Partnerships","الشراكات","Technical and commercial partnerships extend capabilities and market reach."],["04","Made in Oman","صناعة عُمانية","Building technical capability, products and opportunities from Oman."]]},
contact:{e:"LET'S BUILD",a:"لنبنِ معًا",t:"Have an industrial problem worth solving",ta:"لديك تحدٍ صناعي يستحق الحل",i:"Tell us what you are trying to inspect, connect, automate or build. We can explore the technology pathway together.",ia:"أخبرنا بما تريد تفتيشه أو ربطه أو أتمتته أو بناءه، ولنستكشف معًا المسار التقني المناسب.",c:[["01","Technology Partnerships","شراكات تقنية","Co-development, technology transfer and strategic technical collaboration."],["02","Industrial Projects","مشاريع صناعية","Inspection, monitoring, automation and connected-systems requirements."],["03","Product Development","تطوير المنتجات","Move an idea from technical concept toward a validated product pathway."],["04","General Enquiries","استفسارات عامة","Company, partnership and business enquiries."]]},
impact:{e:"TECHNOLOGY WITH PURPOSE",a:"تقنية تصنع أثرًا",t:"Capability building is part of our wider impact",ta:"بناء القدرات جزء من أثرنا الأوسع",i:"Education and talent initiatives may be delivered as complementary social-impact programs, while bxbii's core identity remains deep-tech product and industrial technology.",ia:"يمكن تنفيذ مبادرات التعليم وبناء المواهب كبرامج أثر مجتمعي مكملة، بينما تبقى هوية bxbii الأساسية في المنتجات والتقنيات الصناعية العميقة.",c:[["01","Talent Development","تطوير المواهب","Selected initiatives that expose local talent to emerging technologies."],["02","Industry Awareness","الوعي الصناعي","Practical initiatives connecting people with real industrial challenges."],["03","Knowledge Transfer","نقل المعرفة","Sharing technical knowledge through partnerships and applied initiatives."],["04","Future Capability","قدرات المستقبل","Supporting long-term technical capability in Oman where appropriate."]]}}

function ContactForm(){
 const {lang}=useLanguage(); const ar=lang==="ar"; const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
 const [values,setValues]=useState({name:"",email:"",phone:"",subject:"",message:""});
 const t=(e:string,a:string)=>ar?a:e;
 async function submit(e:FormEvent){e.preventDefault();setStatus("sending");const ok=await publicApi.submitContactForm(values);setStatus(ok?"success":"error");if(ok)setValues({name:"",email:"",phone:"",subject:"",message:""});}
 const input="w-full rounded-2xl border border-white/10 bg-[#091624] px-5 py-4 text-sm text-white outline-none placeholder:text-white/25 focus:border-cyan-200/40";
 return <section className="border-t border-white/10 bg-[#07111a]"><div className={`mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><span className="text-[10px] font-black tracking-[.22em] text-cyan-200">{t("CONTACT BXBII","تواصل مع BXBII")}</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">{t("Send us a message","أرسل لنا رسالة")}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-white/50">{t("Your message is submitted securely to the existing BXBII backend contact inbox.","يتم إرسال رسالتك بأمان إلى صندوق التواصل الحالي في نظام BXBII الخلفي.")}</p><a href="mailto:info@bxbii.com" className="mt-7 inline-block text-sm font-black text-cyan-200">info@bxbii.com</a></div><form onSubmit={submit} className="rounded-[28px] border border-white/10 bg-white/[.025] p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><input required className={input} placeholder={t("Full name","الاسم الكامل")} value={values.name} onChange={e=>setValues(v=>({...v,name:e.target.value}))}/><input required type="email" className={input} placeholder={t("Email address","البريد الإلكتروني")} value={values.email} onChange={e=>setValues(v=>({...v,email:e.target.value}))}/><input className={input} placeholder={t("Phone","رقم الهاتف")} value={values.phone} onChange={e=>setValues(v=>({...v,phone:e.target.value}))}/><input className={input} placeholder={t("Subject","الموضوع")} value={values.subject} onChange={e=>setValues(v=>({...v,subject:e.target.value}))}/></div><textarea required rows={6} className={`mt-4 ${input}`} placeholder={t("Tell us about your project or enquiry","اكتب تفاصيل مشروعك أو استفسارك")} value={values.message} onChange={e=>setValues(v=>({...v,message:e.target.value}))}/><div className={`mt-5 flex flex-wrap items-center gap-4 ${ar?"justify-end":""}`}><button disabled={status==="sending"} type="submit" className="rounded-full bg-gradient-to-r from-red-500 to-orange-400 px-7 py-4 text-sm font-black disabled:opacity-50">{status==="sending"?t("Sending…","جارٍ الإرسال…"):t("Send message","إرسال الرسالة")} →</button>{status==="success"&&<span className="text-sm text-cyan-200">{t("Message received. We will get back to you.","تم استلام رسالتك وسنتواصل معك.")}</span>}{status==="error"&&<span className="text-sm text-red-300">{t("Could not send the message. Please try again.","تعذر إرسال الرسالة، حاول مرة أخرى.")}</span>}</div></form></div></div></section>
}

export function DeepTechPage({page}:{page:PageKey}){const{lang}=useLanguage();const ar=lang==="ar";const d=pages[page];return <main className="min-h-[75vh] bg-[#050b13] text-white"><section className="border-b border-white/10 bg-[radial-gradient(circle_at_80%_10%,rgba(47,183,255,.16),transparent_30%),linear-gradient(135deg,#050b13,#071727)] py-28"><div className={`mx-auto max-w-7xl px-5 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><span className="text-[11px] font-black tracking-[.22em] text-cyan-200">{ar?d.a:d.e}</span><h1 className="mt-5 max-w-5xl text-5xl font-black leading-[1] tracking-[-.04em]">{ar?d.ta:d.t}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/55">{ar?d.ia:d.i}</p><Link href="/contact-us" className="mt-9 inline-flex rounded-full bg-gradient-to-r from-red-500 to-orange-400 px-7 py-4 text-sm font-black">{ar?"ابدأ محادثة":"Start a conversation"} →</Link></div></section><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-2">{d.c.map(([n,en,a,desc])=><article key={n} className={`rounded-[1.5rem] border border-white/10 bg-[#091624] p-8 ${ar?"text-right":""}`}><span className="text-xs font-black text-red-400">{n}</span><h2 className="mt-7 text-2xl font-black">{ar?a:en}</h2><p className="mt-4 text-sm leading-7 text-white/45">{desc}</p><div className="mt-7 h-px bg-gradient-to-r from-red-500/70 via-cyan-300/30 to-transparent"/></article>)}</div></section>{page==="contact"&&<ContactForm/>}</main>}
