"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useLanguage } from "./language-provider";
import { publicApi, type PublicProgram } from "@/lib/public-api";

const slides = [
  { en:"Technology", ar:"التقنية", descEn:"Explore the technology capabilities already published on BXBII.", descAr:"استكشف القدرات التقنية المنشورة حاليًا في BXBII.", href:"/technology", image:"/images/semiconductor-hero.svg", ctaEn:"Explore technology", ctaAr:"استكشف التقنية" },
  { en:"Solutions", ar:"الحلول", descEn:"Discover the solutions and capabilities currently available on the platform.", descAr:"اكتشف الحلول والقدرات المتوفرة حاليًا على المنصة.", href:"/solutions", image:"/images/robotics-industrial.svg", ctaEn:"Explore solutions", ctaAr:"استكشف الحلول" },
  { en:"Industries", ar:"القطاعات", descEn:"See the industries represented across the existing BXBII platform.", descAr:"تعرّف على القطاعات الموجودة ضمن منصة BXBII الحالية.", href:"/industries", image:"/images/iot-connected.svg", ctaEn:"Explore industries", ctaAr:"استكشف القطاعات" },
  { en:"Training", ar:"التدريب", descEn:"One training service containing the published programs and pathways.", descAr:"خدمة تدريب واحدة تضم البرامج والمسارات المنشورة.", href:"/programs", image:"/images/robotics-industrial.svg", ctaEn:"Explore programs", ctaAr:"استكشف البرامج" },
];

export function EnhancedBxbiiHomePage(){
 const {lang}=useLanguage(); const ar=lang==="ar"; const [active,setActive]=useState(0); const [programs,setPrograms]=useState<PublicProgram[]>([]);
 const t=(en:string,a:string)=>ar?a:en;
 useEffect(()=>{publicApi.getPrograms().then(r=>setPrograms(r??[])).catch(()=>setPrograms([])); const timer=window.setInterval(()=>setActive(v=>(v+1)%slides.length),6500); return()=>window.clearInterval(timer)},[]);
 const s=slides[active];
 return <main className="overflow-hidden bg-[#03070d] text-white">
  <section className="relative border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,rgba(36,185,255,.18),transparent_28%),radial-gradient(circle_at_15%_75%,rgba(255,72,48,.10),transparent_26%),linear-gradient(120deg,#02050a,#071321_55%,#02060b)]"/><div className="relative mx-auto max-w-7xl px-5 pb-16 pt-20 sm:px-8 lg:px-10">
   <div className="mb-8 flex items-center justify-between border-y border-white/10 py-3 text-[9px] font-bold uppercase tracking-[.24em] text-white/40"><span>{t("MUSCAT · OMAN","مسقط · عُمان")}</span><span>BXBII</span><span className="hidden sm:block">{t("BUILT FOR THE REAL WORLD","مصممة للعالم الحقيقي")}</span></div>
   <div className="grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]">
    <div className={ar?"text-right":""}><span className="inline-flex rounded-full border border-cyan-200/20 bg-cyan-200/[.04] px-4 py-2 text-[10px] font-black tracking-[.22em] text-cyan-200">BXBII / PLATFORM</span><h1 className="mt-7 text-5xl font-black tracking-[-.06em] sm:text-7xl lg:text-[78px]">{t(s.en,s.ar)}</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/55 sm:text-lg">{t(s.descEn,s.descAr)}</p><div className={`mt-8 flex flex-wrap gap-3 ${ar?"justify-end":""}`}><Link href={s.href} className="rounded-lg bg-gradient-to-r from-red-500 to-orange-400 px-7 py-4 text-sm font-black transition hover:-translate-y-0.5">{t(s.ctaEn,s.ctaAr)} →</Link><Link href="/contact-us" className="rounded-lg border border-white/15 px-7 py-4 text-sm font-black">{t("Contact us","تواصل معنا")}</Link></div><div className={`mt-9 flex gap-2 ${ar?"justify-end":""}`}>{slides.map((x,i)=><button key={x.en} onClick={()=>setActive(i)} aria-label={x.en} className={`h-1.5 rounded-full transition-all ${i===active?"w-12 bg-white":"w-5 bg-white/20"}`}/>)}</div></div>
    <div className="relative h-[430px] overflow-hidden rounded-[2rem] border border-white/10 bg-[#07121d]/70 shadow-2xl">{slides.map((x,i)=><div key={x.en} className={`absolute inset-0 transition duration-700 ${i===active?"opacity-100 scale-100":"pointer-events-none scale-105 opacity-0"}`}><img src={x.image} alt="" className="h-full w-full object-cover p-10 opacity-80"/><div className="absolute inset-0 bg-gradient-to-t from-[#03070d] via-transparent to-transparent"/><div className={`absolute bottom-7 ${ar?"right-7 text-right":"left-7"}`}><span className="text-[10px] font-black tracking-[.2em] text-cyan-200">0{i+1} / {slides.length}</span><h2 className="mt-2 text-3xl font-black">{t(x.en,x.ar)}</h2></div></div>)}<button onClick={()=>setActive((active-1+slides.length)%slides.length)} className="absolute left-4 top-1/2 rounded-full border border-white/15 bg-black/30 p-3">←</button><button onClick={()=>setActive((active+1)%slides.length)} className="absolute right-4 top-1/2 rounded-full border border-white/15 bg-black/30 p-3">→</button></div>
   </div></div></section>

  <section className="border-b border-white/10 bg-[#060d15] py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className={ar?"text-right":""}><span className="text-[10px] font-black tracking-[.25em] text-cyan-200">01 / {t("SERVICES & PRODUCTS","الخدمات والمنتجات")}</span><h2 className="mt-4 text-4xl font-black sm:text-5xl">{t("Explore what is already available.","استكشف ما هو متاح فعليًا.")}</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{slides.map((x,i)=><Link href={x.href} key={x.en} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#091521] transition hover:-translate-y-1 hover:border-cyan-200/30"><div className="h-40 bg-[#0b1b29]"><img src={x.image} alt="" className="h-full w-full object-cover p-8 opacity-70 transition group-hover:scale-105 group-hover:opacity-95"/></div><div className={`p-6 ${ar?"text-right":""}`}><span className="text-[10px] font-black text-red-400">0{i+1}</span><h3 className="mt-2 text-xl font-black">{t(x.en,x.ar)}</h3><p className="mt-3 text-xs leading-6 text-white/40">{t(x.descEn,x.descAr)}</p><span className="mt-5 inline-flex text-xs font-black text-cyan-200">{t("Explore →","استكشف ←")}</span></div></Link>)}</div></div></section>

  <section className="border-b border-white/10 py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className={`flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between ${ar?"text-right":""}`}><div><span className="text-[10px] font-black tracking-[.25em] text-cyan-200">02 / {t("TRAINING","التدريب")}</span><h2 className="mt-4 text-4xl font-black">{t("Training programs","البرامج التدريبية")}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/45">{t("Training is one service. Courses, programs and pathways are content inside it and are displayed from available platform data.","التدريب خدمة واحدة. الدورات والبرامج والمسارات محتوى داخلي لها ويُعرض من بيانات المنصة المتاحة.")}</p></div><Link href="/programs" className="rounded-lg border border-white/15 px-5 py-3 text-xs font-black">{t("View all programs","عرض جميع البرامج")} →</Link></div>{programs.length>0?<div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{programs.slice(0,6).map(p=><Link href={`/programs/${p.slug}`} key={p.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-6 transition hover:border-cyan-200/25"><span className="text-[10px] text-cyan-200">{lang==="ar"?p.arDomain:p.enDomain}</span><h3 className={`mt-2 text-xl font-black ${ar?"text-right":""}`}>{lang==="ar"?p.arName:p.enName}</h3><p className={`mt-3 text-xs leading-6 text-white/40 ${ar?"text-right":""}`}>{lang==="ar"?p.arDescription:p.enDescription}</p><div className={`mt-5 border-t border-white/10 pt-4 text-xs text-white/45 ${ar?"text-right":""}`}>{lang==="ar"?p.arDuration:p.enDuration} · {lang==="ar"?p.arFormat:p.enFormat}</div></Link>)}</div>:<div className="mt-10 rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-white/35">{t("No training programs are currently published.","لا توجد برامج تدريبية منشورة حاليًا.")}</div>}</div></section>

  <section className="bg-[#060d15] py-20"><div className={`mx-auto max-w-7xl px-5 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><div className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#0d1d2d] to-[#050b12] p-8 sm:p-12"><span className="text-[10px] font-black tracking-[.25em] text-red-400">03 / BXBII</span><h2 className="mt-4 text-4xl font-black sm:text-5xl">{t("A clearer way to discover the existing platform.","طريقة أوضح لاكتشاف المنصة الحالية.")}</h2><p className="mt-5 max-w-3xl text-sm leading-7 text-white/45">{t("The enhancement keeps the existing routes, backend, database and public architecture while improving discovery, motion, bilingual UX and responsive presentation.","هذا التطوير يحافظ على المسارات والـBackend وقاعدة البيانات والبنية الحالية، مع تحسين الاكتشاف والحركة وتجربة اللغتين والتجاوب.")}</p></div></div></section>
 </main>;
}
