"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { publicApi, type PublicProgram } from "@/lib/public-api";
import { useLanguage } from "./language-provider";

const slides=[
 {en:"ENGINEERING INTELLIGENCE FOR THE PHYSICAL WORLD",ar:"نهندس الذكاء للعالم الحقيقي",descEn:"Deep technology, industrial systems and advanced capabilities built in Oman for critical industries.",descAr:"تكنولوجيا عميقة وأنظمة صناعية وقدرات متقدمة تُبنى في عُمان للقطاعات الحيوية.",href:"/technology"},
 {en:"FROM OMAN. BUILT FOR INDUSTRY.",ar:"من عُمان. صُممت للصناعة.",descEn:"Technology that connects hardware, software and real-world operations.",descAr:"تقنيات تربط العتاد والبرمجيات والعمليات في العالم الحقيقي.",href:"/solutions"},
 {en:"CAPABILITY THAT MOVES INDUSTRY FORWARD.",ar:"قدرات تدفع الصناعة إلى الأمام.",descEn:"From energy and mining to manufacturing, infrastructure and connected systems.",descAr:"من الطاقة والتعدين إلى التصنيع والبنية الأساسية والأنظمة المتصلة.",href:"/industries"}
];
const capabilities=[
 ["01","Semiconductors","أشباه الموصلات","Advanced chip and integrated hardware capabilities.","/technology"],
 ["02","Robotics & Automation","الروبوتات والأتمتة","Intelligent machines engineered for industrial environments.","/technology"],
 ["03","Connected Systems","الأنظمة المتصلة","IoT, embedded systems and intelligent edge capabilities.","/technology"],
 ["04","Industrial Solutions","الحلول الصناعية","Technology solutions designed around operational outcomes.","/solutions"]
];
const industries=[["Oil & Gas","النفط والغاز"],["Mining & Manufacturing","التعدين والتصنيع"],["Energy & Utilities","الطاقة والمرافق"],["Ports & Infrastructure","الموانئ والبنية الأساسية"]];

export function EnhancedBxbiiHomePage(){
 const {lang}=useLanguage(); const ar=lang==="ar"; const [active,setActive]=useState(0); const [programs,setPrograms]=useState<PublicProgram[]>([]); const t=(e:string,a:string)=>ar?a:e;
 useEffect(()=>{publicApi.getPrograms().then(r=>setPrograms(r??[])).catch(()=>setPrograms([]));const id=window.setInterval(()=>setActive(v=>(v+1)%slides.length),7000);return()=>window.clearInterval(id)},[]);
 const s=slides[active];
 return <main className="overflow-hidden bg-[#05080d] text-white">
  <section className="relative min-h-[760px] overflow-hidden border-b border-white/10">
   <div className="absolute inset-0 bg-[url('/images/oman-hero.webp')] bg-cover bg-center"/>
   <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,7,13,.94)_0%,rgba(3,7,13,.72)_38%,rgba(3,7,13,.18)_75%,rgba(3,7,13,.38)_100%)]"/>
   <div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(3,7,13,.92)_0%,transparent_40%,rgba(3,7,13,.2)_100%)]"/>
   <div className="relative mx-auto flex min-h-[760px] max-w-7xl items-end px-5 pb-20 pt-28 sm:px-8 lg:px-10">
    <div className={`max-w-4xl ${ar?"mr-auto text-right":""}`}>
     <div className="mb-6 flex flex-wrap items-center gap-3 text-[10px] font-black uppercase tracking-[.28em] text-white/70"><span>BXBII</span><span className="h-px w-10 bg-white/40"/><span>{t("MUSCAT · OMAN","مسقط · عُمان")}</span><span className="h-px w-10 bg-white/40"/><span>{t("DEEP TECHNOLOGY COMPANY","شركة تكنولوجيا عميقة")}</span></div>
     <h1 key={active} className="max-w-4xl text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl lg:text-[92px]">{t(s.en,s.ar)}</h1>
     <p className="mt-7 max-w-2xl text-base leading-7 text-white/78 sm:text-xl">{t(s.descEn,s.descAr)}</p>
     <div className={`mt-9 flex flex-wrap gap-3 ${ar?"justify-end":""}`}><Link href={s.href} className="rounded-full bg-white px-7 py-4 text-sm font-black text-[#05080d] transition hover:-translate-y-1">{t("Explore","استكشف")} <span className={ar?"mr-2":"ml-2"}>{ar?"←":"→"}</span></Link><Link href="/contact-us" className="rounded-full border border-white/35 bg-black/15 px-7 py-4 text-sm font-black backdrop-blur">{t("Work with bxbii","تعاون مع bxbii")}</Link></div>
     <div className={`mt-12 flex items-center gap-2 ${ar?"justify-end":""}`}>{slides.map((x,i)=><button key={x.en} onClick={()=>setActive(i)} className={`h-1 rounded-full transition-all ${i===active?"w-14 bg-white":"w-7 bg-white/35"}`} aria-label={`slide ${i+1}`}/>)}</div>
    </div>
   </div>
   <div className="absolute bottom-7 right-5 hidden text-right text-[9px] font-black uppercase tracking-[.22em] text-white/55 sm:block">{t("FROM OMAN TO THE WORLD","من عُمان إلى العالم")}<br/><span className="text-white/30">{t("People · Technology · Industry","الإنسان · التقنية · الصناعة")}</span></div>
  </section>

  <section className="border-b border-white/10 bg-[#070b11] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className={`max-w-3xl ${ar?"mr-auto text-right":""}`}><span className="text-[10px] font-black uppercase tracking-[.28em] text-cyan-200">01 / {t("WHAT WE BUILD","ماذا نبني")}</span><h2 className="mt-5 text-4xl font-black tracking-[-.04em] sm:text-6xl">{t("Technology with the weight of a real company.","تقنية بوزن شركة حقيقية.")}</h2><p className="mt-6 text-sm leading-7 text-white/45 sm:text-base">{t("bxbii combines deep technology, engineering and industry knowledge to build capabilities that can move from concept to deployment.","تجمع bxbii بين التكنولوجيا العميقة والهندسة والمعرفة الصناعية لبناء قدرات تنتقل من الفكرة إلى التطبيق.")}</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{capabilities.map(([n,en,a,d,href])=><Link href={href} key={n} className="group bg-[#080d14] p-7 transition hover:bg-[#0d1722]"><span className="text-[10px] font-black text-red-400">{n}</span><div className="mt-16 text-4xl font-black text-white/15 transition group-hover:text-cyan-200/40">0{n}</div><h3 className={`mt-5 text-xl font-black ${ar?"text-right":""}`}>{t(en,a)}</h3><p className={`mt-3 text-xs leading-6 text-white/40 ${ar?"text-right":""}`}>{t(d,d)}</p><span className={`mt-7 inline-flex text-[10px] font-black uppercase tracking-[.18em] text-white/50 group-hover:text-white ${ar?"float-left":""}`}>{t("Explore →","استكشف ←")}</span></Link>)}</div></div></section>

  <section className="relative border-b border-white/10 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className={`flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between ${ar?"text-right":""}`}><div><span className="text-[10px] font-black uppercase tracking-[.28em] text-red-400">02 / {t("INDUSTRIES","القطاعات")}</span><h2 className="mt-5 text-4xl font-black sm:text-6xl">{t("Built around the industries that matter.","نبني حول القطاعات التي تصنع المستقبل.")}</h2></div><p className="max-w-xl text-sm leading-7 text-white/40">{t("Our focus is practical: critical operations, measurable performance and technology that works in demanding environments.","تركيزنا عملي: عمليات حيوية، أداء قابل للقياس، وتقنيات تعمل في البيئات الصعبة.")}</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2">{industries.map(([en,a],i)=><Link href="/industries" key={en} className="group flex min-h-40 items-end justify-between border-t border-white/10 p-6 transition hover:bg-white/[.025]"><div><span className="text-[10px] font-black text-white/25">0{i+1}</span><h3 className="mt-8 text-2xl font-black">{t(en,a)}</h3></div><span className="text-2xl text-white/25 transition group-hover:translate-x-1 group-hover:text-cyan-200">↗</span></Link>)}</div></div></section>

  <section className="border-b border-white/10 bg-[#070b11] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className={`grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end ${ar?"text-right":""}`}><div><span className="text-[10px] font-black uppercase tracking-[.28em] text-cyan-200">03 / {t("TRAINING","التدريب")}</span><h2 className="mt-5 text-4xl font-black sm:text-6xl">{t("One training service. Serious programs.","خدمة تدريب واحدة. برامج جادة.")}</h2></div><div><p className="max-w-2xl text-sm leading-7 text-white/45">{t("Our training offering connects professional development with the technologies and capabilities needed by industry.","يربط التدريب لدينا التطوير المهني بالتقنيات والقدرات التي تحتاجها الصناعة.")}</p><Link href="/programs" className="mt-7 inline-flex rounded-full border border-white/20 px-6 py-3 text-xs font-black">{t("View training programs","استعرض البرامج التدريبية")} →</Link></div></div>{programs.length>0&&<div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{programs.slice(0,6).map(p=><Link href={`/programs/${p.slug}`} key={p.id} className="group border border-white/10 bg-[#0a1018] p-6 transition hover:-translate-y-1 hover:border-cyan-200/25"><span className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-200">{lang==="ar"?p.arDomain:p.enDomain}</span><h3 className={`mt-4 text-xl font-black ${ar?"text-right":""}`}>{lang==="ar"?p.arName:p.enName}</h3><p className={`mt-3 line-clamp-3 text-xs leading-6 text-white/40 ${ar?"text-right":""}`}>{lang==="ar"?p.arDescription:p.enDescription}</p><div className={`mt-6 border-t border-white/10 pt-4 text-[10px] text-white/35 ${ar?"text-right":""}`}>{lang==="ar"?p.arDuration:p.enDuration} · {lang==="ar"?p.arFormat:p.enFormat}</div></Link>)}</div>}</div></section>

  <section className="relative overflow-hidden py-24 sm:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(40,190,255,.14),transparent_35%)]"/><div className={`relative mx-auto max-w-7xl px-5 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><div className="border-y border-white/10 py-14 sm:py-20"><span className="text-[10px] font-black uppercase tracking-[.28em] text-red-400">04 / BXBII</span><h2 className="mt-5 max-w-5xl text-4xl font-black tracking-[-.04em] sm:text-6xl">{t("Built in Oman. Engineered for the world.","من عُمان. هندسة للعالم.")}</h2><div className="mt-9 flex flex-wrap gap-3"><Link href="/about-us" className="rounded-full bg-white px-7 py-4 text-sm font-black text-[#05080d]">{t("Discover bxbii","اكتشف bxbii")} →</Link><Link href="/contact-us" className="rounded-full border border-white/20 px-7 py-4 text-sm font-black">{t("Start a conversation","ابدأ محادثة")}</Link></div></div></div></section>
 </main>;
}
