"use client";
import Link from "next/link";
import { useLanguage } from "./language-provider";

const items = [
  { ar: "الذكاء الاصطناعي وتطبيقاته", en: "Artificial Intelligence & Applications", catAr: "الذكاء الاصطناعي", catEn: "AI & Data", img: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80", arTime: "8 أسابيع", enTime: "8 weeks" },
  { ar: "تحليل البيانات باستخدام Python", en: "Data Analytics with Python", catAr: "تحليل البيانات", catEn: "Data Analytics", img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80", arTime: "6 أسابيع", enTime: "6 weeks" },
  { ar: "أساسيات الأمن السيبراني", en: "Cybersecurity Fundamentals", catAr: "الأمن السيبراني", catEn: "Cybersecurity", img: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=900&q=80", arTime: "6 أسابيع", enTime: "6 weeks" },
  { ar: "تطوير الويب المتكامل", en: "Full Stack Web Development", catAr: "تطوير البرمجيات", catEn: "Software Development", img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80", arTime: "12 أسبوعًا", enTime: "12 weeks" },
  { ar: "إدارة المشاريع الاحترافية", en: "Professional Project Management", catAr: "إدارة الأعمال", catEn: "Business & Management", img: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80", arTime: "6 أسابيع", enTime: "6 weeks" },
  { ar: "الحوسبة السحابية", en: "Cloud Computing", catAr: "الحوسبة السحابية", catEn: "Cloud Computing", img: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80", arTime: "8 أسابيع", enTime: "8 weeks" },
];

export function HomePage() {
  const { lang } = useLanguage(); const ar = lang === "ar";
  const t = (en: string, a: string) => ar ? a : en;
  return <main className="bg-white text-slate-950">
    <section className="relative min-h-[680px] overflow-hidden bg-[#06172f] text-white">
      <img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2200&q=85" alt="Modern learning environment" className="absolute inset-0 h-full w-full object-cover opacity-45" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,#041226_5%,rgba(4,18,38,.94)_38%,rgba(4,18,38,.30)_100%)]" />
      <div className="relative mx-auto flex min-h-[680px] max-w-7xl items-center px-5 py-24 sm:px-8 lg:px-10"><div className={`max-w-3xl ${ar ? "text-right" : ""}`}>
        <span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold tracking-[.18em] backdrop-blur">{t("PEOPLE • SKILLS • TECHNOLOGY","الإنسان • المهارات • التقنية")}</span>
        <h1 className="mt-7 text-5xl font-black leading-[1.02] sm:text-6xl lg:text-7xl">{t("The future of skills starts here.","مستقبل المهارات يبدأ من هنا.")}</h1>
        <p className="mt-7 max-w-2xl text-lg leading-8 text-white/75 sm:text-xl">{t("Specialized programs, practical bootcamps and professional courses for people and organizations ready for what is next.","برامج متخصصة ومعسكرات عملية ودورات مهنية للأفراد والمؤسسات المستعدين للمرحلة القادمة.")}</p>
        <div className={`mt-9 flex flex-wrap gap-3 ${ar ? "justify-end" : ""}`}><Link href="/programs" className="rounded-full bg-blue-600 px-7 py-4 font-black hover:bg-blue-500">{t("Explore programs","استكشف البرامج")} →</Link><Link href="/courses" className="rounded-full border border-white/25 bg-white/10 px-7 py-4 font-black">{t("Explore courses","استكشف الدورات")}</Link></div>
        <div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-4">{[["50+","برامج","50+","Programs"],["10K+","متعلم","10K+","Learners"],["25+","شريك","25+","Partners"],["95%","رضا","95%","Satisfaction"]].map(([a,aa,e,ee])=><div key={e} className="border-s border-white/15 ps-4"><b className="block text-2xl">{ar?a:e}</b><span className="text-xs text-white/55">{ar?aa:ee}</span></div>)}</div>
      </div></div>
    </section>
    <section className="border-b border-slate-200 bg-white py-8"><div className="mx-auto grid max-w-7xl gap-4 px-5 sm:px-8 md:grid-cols-4 lg:px-10">{[["01","Learn by doing","تعلّم بالممارسة"],["02","Industry aligned","متوافق مع احتياجات القطاع"],["03","Bilingual","ثنائي اللغة"],["04","Global standard","معيار عالمي"]].map(([n,e,a])=><div key={n} className={`rounded-2xl bg-slate-50 p-5 ${ar?"text-right":""}`}><span className="text-xs font-black text-blue-600">{n}</span><h3 className="mt-2 font-black">{ar?a:e}</h3></div>)}</div></section>
    <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className={ar?"text-right":""}><span className="text-xs font-black tracking-[.18em] text-blue-600">{t("FEATURED PROGRAMS","البرامج التدريبية")}</span><h2 className="mt-3 text-4xl font-black sm:text-5xl">{t("Programs built for the real world","برامج صُممت للعالم الحقيقي")}</h2><p className="mt-4 text-slate-500">{t("Practical learning across technology, data, business and digital skills.","تعلم عملي في التقنية والبيانات والأعمال والمهارات الرقمية.")}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(x=><article key={x.en} className="group overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm hover:-translate-y-1 hover:shadow-xl"><div className="relative h-48 overflow-hidden"><img src={x.img} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent"/><span className={`absolute bottom-4 rounded-full bg-white/15 px-3 py-1 text-xs font-bold text-white backdrop-blur ${ar?"right-5":"left-5"}`}>{ar?x.catAr:x.catEn}</span></div><div className={`p-6 ${ar?"text-right":""}`}><h3 className="text-xl font-black">{ar?x.ar:x.en}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{t("Practical curriculum, guided projects and clear outcomes.","منهج عملي ومشاريع تطبيقية ومخرجات واضحة.")}</p><div className="mt-5 flex justify-between border-t pt-4 text-xs font-bold text-slate-400"><span>{ar?x.arTime:x.enTime}</span><Link href="/courses" className="text-blue-700">{t("View course","عرض الدورة")} →</Link></div></div></article>)}</div></div></section>
    <section className="bg-white py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-2 lg:px-10"><div className="overflow-hidden rounded-[2rem] bg-slate-900"><img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=85" alt="Learners collaborating" className="h-full min-h-[430px] w-full object-cover opacity-65"/></div><div className={`flex flex-col justify-center ${ar?"text-right":""}`}><span className="text-xs font-black tracking-[.18em] text-blue-600">{t("OUR METHOD","منهجنا")}</span><h2 className="mt-4 text-4xl font-black sm:text-5xl">{t("Learn. Apply. Build. Grow.","تعلّم. طبّق. ابنِ. تطوّر.")}</h2><p className="mt-5 text-lg leading-8 text-slate-500">{t("We connect knowledge to practice, projects and measurable outcomes.","نربط المعرفة بالتطبيق والمشاريع والمخرجات القابلة للقياس.")}</p><div className="mt-8 grid grid-cols-2 gap-3">{[["01","Learn","تعلّم"],["02","Apply","طبّق"],["03","Build","ابنِ"],["04","Grow","تطوّر"]].map(([n,e,a])=><div key={n} className="rounded-xl border bg-slate-50 p-4 font-bold"><span className="me-3 text-blue-600">{n}</span>{ar?a:e}</div>)}</div></div></div></section>
    <section className="bg-[#07172f] py-24 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-2 lg:px-10"><div className={ar?"text-right":""}><span className="text-xs font-black tracking-[.18em] text-blue-300">bxbii ecosystem</span><h2 className="mt-5 text-4xl font-black sm:text-5xl">{t("Local roots. Global standard.","جذور محلية. معيار عالمي.")}</h2><p className="mt-5 text-lg leading-8 text-white/65">{t("Built in Oman for learners, organizations and partners.","نبني bxbii في عُمان للمتعلمين والمؤسسات والشركاء.")}</p></div><div className="grid grid-cols-2 gap-4">{[["01","People","الإنسان"],["02","Skills","المهارات"],["03","Opportunity","الفرص"],["04","Impact","الأثر"]].map(([n,e,a])=><div key={n} className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><span className="text-blue-300">{n}</span><h3 className="mt-8 text-xl font-black">{ar?a:e}</h3></div>)}</div></div></section>
    <section className="bg-blue-600 px-5 py-20 text-white"><div className={`mx-auto flex max-w-7xl flex-col justify-between gap-7 sm:flex-row sm:items-center ${ar?"sm:flex-row-reverse":""}`}><div className={ar?"text-right":""}><h2 className="text-4xl font-black">{t("Ready to start your journey?","جاهز تبدأ رحلتك؟")}</h2><p className="mt-3 text-white/75">{t("Choose a program, start a course or talk to our team.","اختر برنامجًا، ابدأ دورة، أو تواصل مع فريقنا.")}</p></div><Link href="/programs" className="rounded-full bg-white px-7 py-4 font-black text-blue-700">{t("Start learning","ابدأ التعلم")} →</Link></div></section>
  </main>;
}
