"use client";
import Link from "next/link";
import { useLanguage } from "./language-provider";

type Program = { id:string; domain:{en:string;ar:string}; name:{en:string;ar:string}; description:{en:string;ar:string}; duration:{en:string;ar:string}; format:{en:string;ar:string}; status:"open"|"comingSoon"; href?:string };

export function TechnologyProgramsPage({ programs=[] }: { programs?: Program[] }) {
 const {lang}=useLanguage(); const ar=lang==="ar"; const t=(e:string,a:string)=>ar?a:e;
 return <main className="min-h-screen bg-[#050b13] text-white"><section className="border-b border-white/10 bg-[radial-gradient(circle_at_80%_10%,rgba(47,183,255,.16),transparent_30%),linear-gradient(135deg,#050b13,#071727)] py-24"><div className={`mx-auto max-w-7xl px-5 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><span className="text-[10px] font-black tracking-[.25em] text-cyan-200">{t("TRAINING","التدريب")}</span><h1 className="mt-5 max-w-5xl text-5xl font-black tracking-[-.05em] sm:text-7xl">{t("Professional training programs.","برامج تدريبية احترافية.")}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/50">{t("Training is one BXBII service. Programs, courses and pathways are published inside it and use the platform's available data.","التدريب خدمة واحدة في BXBII. وتندرج داخلها البرامج والدورات والمسارات اعتمادًا على البيانات المتاحة في المنصة.")}</p><Link href="/programs" className="mt-8 inline-flex rounded-lg bg-gradient-to-r from-red-500 to-orange-400 px-6 py-3 text-sm font-black">{t("Browse programs","استعرض البرامج")} →</Link></div></section><section className="py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">{programs.length===0?<div className="rounded-2xl border border-dashed border-white/15 p-10 text-center text-white/35">{t("No programs are currently published.","لا توجد برامج منشورة حاليًا.")}</div>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{programs.map(p=><Link href={p.href||"/programs"} key={p.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-7 transition hover:-translate-y-1 hover:border-cyan-200/25"><span className="text-[10px] text-cyan-200">{lang==="ar"?p.domain.ar:p.domain.en}</span><h2 className="mt-2 text-xl font-black">{lang==="ar"?p.name.ar:p.name.en}</h2><p className="mt-3 text-sm leading-6 text-white/40">{lang==="ar"?p.description.ar:p.description.en}</p><div className="mt-5 border-t border-white/10 pt-4 text-xs text-white/45">{lang==="ar"?p.duration.ar:p.duration.en} · {lang==="ar"?p.format.ar:p.format.en}</div></Link>)}</div>}</div></section></main>;
}
