"use client";
import Link from "next/link";
import { useLanguage } from "./language-provider";

type Program={id:string;domain:{en:string;ar:string};name:{en:string;ar:string};description:{en:string;ar:string};duration:{en:string;ar:string};format:{en:string;ar:string};status:"open"|"comingSoon";href?:string};
export function TechnologyProgramsPage({programs=[]}:{programs?:Program[]}){
 const {lang}=useLanguage(); const ar=lang==="ar"; const t=(e:string,a:string)=>ar?a:e;
 return <main className="min-h-screen overflow-hidden bg-[#05080d] text-white">
  <section className="relative min-h-[560px] overflow-hidden border-b border-white/10">
   <div className="absolute inset-0 bg-[url('/images/oman-hero.webp')] bg-cover bg-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,7,13,.95)_0%,rgba(3,7,13,.78)_40%,rgba(3,7,13,.28)_80%,rgba(3,7,13,.5)_100%)]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(3,7,13,.95),transparent_60%)]"/>
   <div className={`relative mx-auto flex min-h-[560px] max-w-7xl items-end px-5 pb-20 pt-32 sm:px-8 lg:px-10 ${ar?"text-right":""}`}>
    <div className="max-w-4xl"><span className="inline-flex rounded-full border border-cyan-200/20 bg-cyan-200/5 px-4 py-2 text-[10px] font-black tracking-[.24em] text-cyan-100">{t("TRAINING","التدريب")}</span><h1 className="mt-6 text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[82px]">{t("Professional technology programs","برامج تقنية احترافية")}</h1><p className="mt-7 max-w-3xl text-base leading-8 text-white/60 sm:text-lg">{t("Training is one BXBII service, connecting learners with practical technology programs and pathways.","التدريب خدمة واحدة في BXBII، تربط المتدربين ببرامج تقنية عملية ومسارات تطويرية.")}</p><Link href="/programs" className="mt-9 inline-flex rounded-full bg-gradient-to-r from-red-500 to-orange-400 px-7 py-4 text-sm font-black">{t("Browse programs","استعرض البرامج")} <span className="ms-2">→</span></Link></div>
   </div>
  </section>
  <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28">
   <div className={`mb-12 ${ar?"text-right":""}`}><span className="text-[10px] font-black tracking-[.24em] text-red-400">{t("PROGRAMS","البرامج")}</span><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">{t("Built around real technology skills","مصممة حول مهارات تقنية حقيقية")}</h2></div>
   {programs.length===0?<div className="rounded-[28px] border border-dashed border-white/15 bg-white/[.02] p-12 text-center text-white/40">{t("No programs are currently published.","لا توجد برامج منشورة حاليًا.")}</div>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{programs.map((p,i)=><Link href={p.href||"/programs"} key={p.id} className={`group rounded-[28px] border border-white/10 bg-white/[.025] p-7 transition duration-300 hover:-translate-y-1 hover:border-cyan-200/25 hover:bg-white/[.045] sm:p-8 ${ar?"text-right":""}`}><div className="flex items-start justify-between gap-5"><span className="text-xs font-black text-red-400">{String(i+1).padStart(2,"0")}</span><span className="text-[10px] font-black tracking-[.15em] text-cyan-200">{ar?p.domain.ar:p.domain.en}</span></div><h3 className="mt-12 text-2xl font-black">{ar?p.name.ar:p.name.en}</h3><p className="mt-4 text-sm leading-7 text-white/45">{ar?p.description.ar:p.description.en}</p><div className="mt-8 flex flex-wrap gap-2 border-t border-white/10 pt-5 text-xs text-white/45"><span>{ar?p.duration.ar:p.duration.en}</span><span>·</span><span>{ar?p.format.ar:p.format.en}</span></div></Link>)}</div>}
  </section>
  <section className="border-t border-white/10 bg-[#07111a]"><div className={`mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10 ${ar?"text-right":""}`}><div className="flex flex-col justify-between gap-7 rounded-[30px] border border-white/10 bg-white/[.025] p-8 sm:p-10 lg:flex-row lg:items-center"><div><span className="text-[10px] font-black tracking-[.24em] text-cyan-200">{t("ONE SERVICE","خدمة واحدة")}</span><h2 className="mt-3 text-3xl font-black">{t("Training, integrated into the bxbii ecosystem","التدريب، ضمن منظومة bxbii المتكاملة")}</h2></div><Link href="/contact-us" className="inline-flex w-fit rounded-full border border-white/15 px-6 py-3 text-sm font-black transition hover:border-cyan-200/40">{t("Contact us","تواصل معنا")} →</Link></div></div></section>
 </main>
}
