export type Bilingual = { en: string; ar: string };
export type CatalogProgram = { slug: string; domain: Bilingual; name: Bilingual; description: Bilingual; duration: Bilingual; level: Bilingual; type: Bilingual };
export type CatalogCourse = { slug: string; category: Bilingual; name: Bilingual; description: Bilingual; duration: Bilingual; lessons: Bilingual[] };

export const catalogPrograms: CatalogProgram[] = [
  { slug: "full-stack-web", domain: { en: "Software Development", ar: "تطوير البرمجيات" }, name: { en: "Full-Stack Web Development", ar: "تطوير الويب المتكامل" }, description: { en: "Build modern web applications from interface to API, database and deployment.", ar: "ابنِ تطبيقات ويب حديثة من الواجهة إلى واجهات البرمجة وقواعد البيانات والنشر." }, duration: { en: "12 weeks", ar: "12 أسبوعًا" }, level: { en: "Beginner → Intermediate", ar: "مبتدئ ← متوسط" }, type: { en: "Bootcamp", ar: "معسكر" } },
  { slug: "ai-applied", domain: { en: "AI & Data", ar: "الذكاء الاصطناعي والبيانات" }, name: { en: "Applied AI & Intelligent Applications", ar: "الذكاء الاصطناعي والتطبيقات الذكية" }, description: { en: "Learn practical AI concepts and build useful workflows with data, models and automation.", ar: "تعلّم مفاهيم الذكاء الاصطناعي العملية وابنِ حلولًا مفيدة بالبيانات والنماذج والأتمتة." }, duration: { en: "8 weeks", ar: "8 أسابيع" }, level: { en: "Intermediate", ar: "متوسط" }, type: { en: "Program", ar: "برنامج" } },
  { slug: "data-analytics", domain: { en: "Data", ar: "البيانات" }, name: { en: "Data Analytics & Decision Intelligence", ar: "تحليل البيانات وذكاء القرار" }, description: { en: "Turn business data into dashboards, insights and decisions.", ar: "حوّل بيانات الأعمال إلى لوحات مؤشرات ورؤى وقرارات." }, duration: { en: "10 weeks", ar: "10 أسابيع" }, level: { en: "Beginner → Intermediate", ar: "مبتدئ ← متوسط" }, type: { en: "Program", ar: "برنامج" } },
  { slug: "cybersecurity-foundations", domain: { en: "Cybersecurity", ar: "الأمن السيبراني" }, name: { en: "Cybersecurity Foundations", ar: "أساسيات الأمن السيبراني" }, description: { en: "Understand networks, identity, threats and secure practices.", ar: "افهم الشبكات والهوية والتهديدات والممارسات الآمنة." }, duration: { en: "8 weeks", ar: "8 أسابيع" }, level: { en: "Beginner", ar: "مبتدئ" }, type: { en: "Program", ar: "برنامج" } },
  { slug: "cloud-fundamentals", domain: { en: "Cloud Computing", ar: "الحوسبة السحابية" }, name: { en: "Cloud Foundations & AWS", ar: "أساسيات الحوسبة السحابية وAWS" }, description: { en: "Learn cloud architecture, security, storage, compute and deployment.", ar: "تعلّم بنية السحابة والأمن والتخزين والحوسبة والنشر." }, duration: { en: "8 weeks", ar: "8 أسابيع" }, level: { en: "Beginner", ar: "مبتدئ" }, type: { en: "Program", ar: "برنامج" } },
  { slug: "project-management", domain: { en: "Business", ar: "الأعمال" }, name: { en: "Project Management in Practice", ar: "إدارة المشاريع بالتطبيق" }, description: { en: "Plan, deliver and report projects using practical methods.", ar: "خطط ونفّذ وراقب المشاريع باستخدام أساليب عملية." }, duration: { en: "6 weeks", ar: "6 أسابيع" }, level: { en: "Intermediate", ar: "متوسط" }, type: { en: "Program", ar: "برنامج" } },
  { slug: "ux-ui", domain: { en: "Digital Design", ar: "التصميم الرقمي" }, name: { en: "UX/UI Product Design", ar: "تصميم المنتجات وتجربة المستخدم" }, description: { en: "Research, prototype and test digital products around real user needs.", ar: "ابحث وصمّم النماذج الأولية واختبر المنتجات الرقمية." }, duration: { en: "4 weeks", ar: "4 أسابيع" }, level: { en: "Beginner", ar: "مبتدئ" }, type: { en: "Short Program", ar: "برنامج قصير" } },
];

export const catalogCourses: CatalogCourse[] = [
  { slug: "python-for-work", category: { en: "Software", ar: "البرمجيات" }, name: { en: "Python for Work & Automation", ar: "بايثون للعمل والأتمتة" }, description: { en: "A practical introduction to Python for data and automation.", ar: "مقدمة عملية إلى بايثون للبيانات والأتمتة." }, duration: { en: "6 hours", ar: "6 ساعات" }, lessons: [{ en: "Python essentials", ar: "أساسيات بايثون" }, { en: "Conditions, loops and functions", ar: "الشروط والحلقات والدوال" }, { en: "Files and structured data", ar: "الملفات والبيانات المنظمة" }, { en: "Automation scripts", ar: "سكربتات الأتمتة" }] },
  { slug: "data-storytelling", category: { en: "Data", ar: "البيانات" }, name: { en: "Data Storytelling & Dashboards", ar: "سرد البيانات ولوحات المؤشرات" }, description: { en: "Turn raw information into clear visual stories.", ar: "حوّل المعلومات الخام إلى قصص بصرية واضحة." }, duration: { en: "5 hours", ar: "5 ساعات" }, lessons: [{ en: "From question to metric", ar: "من السؤال إلى المؤشر" }, { en: "Preparing business data", ar: "تجهيز بيانات الأعمال" }, { en: "Choosing the right visual", ar: "اختيار التمثيل البصري" }, { en: "Decision-ready dashboards", ar: "لوحات مؤشرات جاهزة للقرار" }] },
  { slug: "cyber-hygiene", category: { en: "Cybersecurity", ar: "الأمن السيبراني" }, name: { en: "Cyber Hygiene for Professionals", ar: "الأمن السيبراني للمهنيين" }, description: { en: "Everyday practices for protecting accounts, devices and information.", ar: "ممارسات يومية لحماية الحسابات والأجهزة والمعلومات." }, duration: { en: "3 hours", ar: "3 ساعات" }, lessons: [{ en: "Passwords and MFA", ar: "كلمات المرور والمصادقة متعددة العوامل" }, { en: "Phishing and social engineering", ar: "التصيد والهندسة الاجتماعية" }, { en: "Device security", ar: "أمن الأجهزة" }, { en: "Incident reporting", ar: "الإبلاغ عن الحوادث" }] },
  { slug: "ai-literacy", category: { en: "AI", ar: "الذكاء الاصطناعي" }, name: { en: "AI Literacy for Business", ar: "أساسيات الذكاء الاصطناعي للأعمال" }, description: { en: "Understand AI capabilities, limitations and practical opportunities.", ar: "افهم قدرات الذكاء الاصطناعي وحدوده وفرص استخدامه." }, duration: { en: "4 hours", ar: "4 ساعات" }, lessons: [{ en: "AI concepts", ar: "مفاهيم الذكاء الاصطناعي" }, { en: "Generative AI", ar: "الذكاء الاصطناعي التوليدي" }, { en: "Prompting and workflows", ar: "صياغة التعليمات وسير العمل" }, { en: "Business use cases", ar: "حالات الاستخدام في الأعمال" }] },
];
